/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.semi.view;

import com.semi.person.model.PersonDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ezen
 */
public class FindIdPassword extends javax.swing.JFrame implements ActionListener{
    private PersonDAO personDao;
    /** Creates new form FindIdPassword */
    public FindIdPassword() {
        initComponents();
        
        init();
        addEvent();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbFindId = new javax.swing.JRadioButton();
        rbFindPwd = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tfNameId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHpId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfHpPwd = new javax.swing.JTextField();
        tfIdPwd = new javax.swing.JTextField();
        btClose = new javax.swing.JButton();
        btFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("아이디 비밀번호 찾기");

        buttonGroup1.add(rbFindId);
        rbFindId.setText("아이디 찾기");

        buttonGroup1.add(rbFindPwd);
        rbFindPwd.setText("비밀번호 찾기");

        jLabel1.setText("이름");

        jLabel2.setText("휴대전화 ex) 010-0000-0000");

        jLabel3.setText("아이디");

        jLabel4.setText("휴대전화 ex) 010-0000-0000");

        btClose.setText("닫기");

        btFind.setText("찾기");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFindPwd)
                            .addComponent(rbFindId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(tfNameId, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                .addComponent(tfHpId))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfHpPwd)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btFind, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rbFindId)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(tfNameId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(tfHpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rbFindPwd)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfIdPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(tfHpPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFind)
                    .addComponent(btClose))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindIdPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindIdPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindIdPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindIdPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindIdPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btFind;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbFindId;
    private javax.swing.JRadioButton rbFindPwd;
    private javax.swing.JTextField tfHpId;
    private javax.swing.JTextField tfHpPwd;
    private javax.swing.JTextField tfIdPwd;
    private javax.swing.JTextField tfNameId;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        personDao= new PersonDAO();
    }

    private void addEvent() {
        btClose.addActionListener(this);
        btFind.addActionListener(this);
        tfNameId.addKeyListener(new EventHandler());
        tfHpId.addKeyListener(new EventHandler());
        tfHpPwd.addKeyListener(new EventHandler());
        tfIdPwd.addKeyListener(new EventHandler());
    }
    
    class EventHandler extends KeyAdapter{

        @Override
        public void keyPressed(KeyEvent e) {
            if(e.getSource()==tfNameId || e.getSource()==tfHpId){
                rbFindId.setSelected(true);
            }else if(e.getSource()==tfIdPwd || e.getSource()==tfHpPwd){
                rbFindPwd.setSelected(true);
            }
        }
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btFind){
            try {
                if(rbFindId.isSelected()){
                    findId();
                }else if(rbFindPwd.isSelected()){
                    findPwd();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else if(e.getSource()==btClose){
            this.dispose();
        }
    }

    private void findId() throws SQLException {
        String name=tfNameId.getText();
        String hp=tfHpId.getText();
        
        String id=personDao.selectById2(name,hp);
        
        if(id!=null && !id.isEmpty() ){
            JOptionPane.showMessageDialog(this, "아이디는 "+ id+ " 입니다.");
        }else{
            JOptionPane.showMessageDialog(this, "해당 정보의 아이디가 존재하지 않습니다.");
        }
        
    }

    private void findPwd() throws SQLException {
        String id=tfIdPwd.getText();
        String hp=tfHpPwd.getText();
        
        if(id==null || id.isEmpty()){
            JOptionPane.showMessageDialog(this, "아이디를 입력해주세요.");
            return;
        }else if(hp==null || hp.isEmpty()){
            JOptionPane.showMessageDialog(this, "휴대전화를 입력해주세요.");
            return;
        }
        
        String pwd=personDao.selectByPwd(id,hp);
        
        if(pwd==null || pwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "잘못 입력 했거나 아이디가 존재하지 않습니다.");
        }else{
            JOptionPane.showMessageDialog(this, "비밀번호는"+pwd+" 입니다.");
        }
        
    }

}
