/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.semi.view;

import com.semi.board.model.BoardDAO;
import com.semi.board.model.BoardService;
import com.semi.market.model.MarketDAO;
import com.semi.market.model.MarketService;
import com.semi.view.model.ViewDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezen
 */
public class MainGUI extends javax.swing.JFrame implements ActionListener{
    private DefaultTableModel model=new DefaultTableModel();
    private DefaultTableModel model2=new DefaultTableModel();

    /** Creates new form MainGUI */
    public MainGUI() {
        initComponents();
        
        init();
        addEvent();
    }
    
    class EventHandler extends MouseAdapter{

        @Override
        public void mousePressed(MouseEvent e) {
            if(e.getSource()==tbProduct){
                int row=tbProduct.getSelectedRow();
                Object objNo=tbProduct.getValueAt(row, 0);
                int no = Integer.parseInt((String)objNo);

                MarketService ms=new MarketService(no);
                MarketDetailGUI f = new MarketDetailGUI();
                f.show();
                
            }else if(e.getSource()==tbBoard){
                int row=tbBoard.getSelectedRow();
                Object objNo=tbBoard.getValueAt(row, 0);
                int no = Integer.parseInt((String)objNo);
                
                BoardService.setBno(no);
                ReadBoardGUI f =new ReadBoardGUI();
                f.show();
            }
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMarket = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBoard = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btMain = new javax.swing.JButton();
        btMydata = new javax.swing.JButton();
        btBoard = new javax.swing.JButton();
        btOrderDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("메인화면");

        btMarket.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btMarket.setText("마켓");

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "이미지", "상품명", "가격"
            }
        ));
        jScrollPane1.setViewportView(tbProduct);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "카테고리", "묘/견", "제목", "작성자", "작성일", "조회"
            }
        ));
        jScrollPane2.setViewportView(tbBoard);

        jLabel2.setText("전체 글보기");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("최신 상품");

        btMain.setBackground(new java.awt.Color(204, 255, 255));
        btMain.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btMain.setText("홈");

        btMydata.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btMydata.setText("내 정보");

        btBoard.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btBoard.setText("게시판");

        btOrderDetails.setText("주문내역");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOrderDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMain, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMydata, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMydata, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrderDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBoard;
    private javax.swing.JButton btMain;
    private javax.swing.JButton btMarket;
    private javax.swing.JButton btMydata;
    private javax.swing.JButton btOrderDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBoard;
    private javax.swing.JTable tbProduct;
    // End of variables declaration//GEN-END:variables

    private void addEvent() {
        btBoard.addActionListener(this);
        btMarket.addActionListener(this);
        btMydata.addActionListener(this);
        tbBoard.addMouseListener(new EventHandler());
        tbProduct.addMouseListener(new EventHandler());
        btOrderDetails.addActionListener(this);
    }

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        getContentPane().setBackground(Color.white);
        
        try {
            boardShowAll();
            marketShowAll();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btBoard){
            BoarderGUI f=new BoarderGUI();
            f.show();
            
        }else if(e.getSource()==btMarket){
            MarketMainGUI f=new MarketMainGUI();
            f.show();
            
        }else if(e.getSource()==btMydata){
            MemberInfo f =new MemberInfo();
            f.show();
            
        }else if(e.getSource()==btOrderDetails){
            OrderDetailsGUI f =new OrderDetailsGUI();
            f.show();
            
        }
    }

    private void marketShowAll() throws SQLException{
        MarketDAO marketDao=new MarketDAO();
        
        List<ViewDTO> list = marketDao.pdSelectTop20();
        
        Object[] colNames={"번호","상품명","가격"};
        Object[][] data= new Object[list.size()][colNames.length];
        for(int i=0;i<list.size();i++){
            ViewDTO dto=list.get(i);
            
            data[i][0]=dto.getPdno()+"";
            data[i][1]=dto.getPdName();
            data[i][2]=dto.getPrice()+"";
        }
        model2.setDataVector(data, colNames);
        tbProduct.setModel(model2);
    }

    private void  boardShowAll() throws SQLException {
        BoardDAO boardDao=new BoardDAO();
        List<ViewDTO> list=boardDao.bdSelectTop20();
        
        String[] colNames={"번호","카테고리","묘/견","제목","작성자","작성일","조회"};
        String[][] data=new String[list.size()][colNames.length];
        for(int i=0;i<list.size();i++){
            ViewDTO dto=list.get(i);
            
            data[i][0]=dto.getBno()+"";
            data[i][1]=dto.getBcategory1();
            data[i][2]=dto.getBcategory3();
            data[i][3]=dto.getBtitle();
            data[i][4]=dto.getId();
            data[i][5]=dto.getBregdate()+"";
            data[i][6]=dto.getBviewcnt()+"";
        }
        
        model.setDataVector(data, colNames);
        tbBoard.setModel(model);
    }



}
