/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.semi.view;

import com.semi.basket.model.BasketDAO;
import com.semi.basket.model.BasketDTO;
import com.semi.market.model.MarketDAO;
import com.semi.market.model.MarketService;
import com.semi.person.model.PersonService;
import com.semi.reviews.model.ReviewsDAO;
import com.semi.view.model.ViewDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezen
 */
public class MarketDetailGUI extends javax.swing.JFrame implements ActionListener{
    private MarketDAO marketDao;
    private DefaultTableModel model=new DefaultTableModel();
    /**
     * Creates new form MarketDetailGUI
     */
    public MarketDetailGUI() {
        initComponents();
        
        init();
        addEvent();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfpdName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfqty = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfSumPrice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfFSize = new javax.swing.JTextField();
        tfEatage = new javax.swing.JTextField();
        tfKcal = new javax.swing.JTextField();
        tfPredisease = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfGrade = new javax.swing.JTextField();
        btBasket = new javax.swing.JButton();
        btBuy = new javax.swing.JButton();
        btMydata = new javax.swing.JButton();
        btMarket = new javax.swing.JButton();
        btBoard = new javax.swing.JButton();
        btMain = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReviews = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("상품 화면");

        jLabel2.setText("상품명");

        jLabel3.setText("수량");

        jLabel4.setText("가격");

        tfpdName.setEditable(false);

        jLabel5.setText("총 주문금액");

        tfPrice.setEditable(false);

        tfSumPrice.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("상품 설명"));

        jLabel6.setText("알갱이");

        jLabel7.setText("급여연령");

        jLabel8.setText("칼로리");

        jLabel9.setText("질병예방");

        tfFSize.setEditable(false);

        tfEatage.setEditable(false);

        tfKcal.setEditable(false);

        tfPredisease.setEditable(false);

        jLabel1.setText("평점");

        tfGrade.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPredisease, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(tfKcal)
                    .addComponent(tfEatage)
                    .addComponent(tfFSize)
                    .addComponent(tfGrade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfFSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfEatage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfPredisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        btBasket.setText("장바구니 담기");

        btBuy.setText("구매");

        btMydata.setText("내정보");

        btMarket.setText("마켓");

        btBoard.setText("게시판");

        btMain.setText("홈");

        tbReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbReviews);

        jLabel11.setText("리뷰");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\nb_semi_ws\\semiapp\\img\\KakaoTalk_20230606_162806281.png")); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btMain, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btMydata, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(tfSumPrice)
                                            .addComponent(tfpdName)
                                            .addComponent(tfqty))
                                        .addGap(12, 12, 12)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMydata, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btMarket, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(btMain, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfSumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBasket)
                    .addComponent(btBuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketDetailGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBasket;
    private javax.swing.JButton btBoard;
    private javax.swing.JButton btBuy;
    private javax.swing.JButton btMain;
    private javax.swing.JButton btMarket;
    private javax.swing.JButton btMydata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbReviews;
    private javax.swing.JTextField tfEatage;
    private javax.swing.JTextField tfFSize;
    private javax.swing.JTextField tfGrade;
    private javax.swing.JTextField tfKcal;
    private javax.swing.JTextField tfPredisease;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfSumPrice;
    private javax.swing.JTextField tfpdName;
    public static javax.swing.JTextField tfqty;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        marketDao=new MarketDAO();
        tfqty.setText("1");
            try {
                showPd();
                showPdReview();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        tfSumPrice.setText(tfPrice.getText());
    }

    private void addEvent() {
        btBasket.addActionListener(this);
        btBoard.addActionListener(this);
        btMain.addActionListener(this);
        btMydata.addActionListener(this);
        btMarket.addActionListener(this);
        btBuy.addActionListener(this);
        tfqty.addKeyListener(new EventHanler());
    }

    class EventHanler extends KeyAdapter{

        @Override
        public void keyReleased(KeyEvent e) {
            String strQty=tfqty.getText();
            if(strQty==null || strQty.isEmpty()){
                strQty="0";
            }
            
            int qty=Integer.parseInt(strQty);
            int price=Integer.parseInt(tfPrice.getText());
            
            tfSumPrice.setText(qty*price+"");
        }
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btBoard){
            BoarderGUI f =new BoarderGUI();
            f.show();
            this.dispose();
        }else if(e.getSource()==btMain){
            this.dispose();
        }else if(e.getSource()==btMarket){
            MarketMainGUI f = new MarketMainGUI();
            f.show();
            this.dispose();
        }else if(e.getSource()==btMydata){
            MemberInfo f =new MemberInfo();
            f.show();
            this.dispose();
        }else if(e.getSource()==btBuy){
            MarketService ms =new MarketService(tfpdName.getText(),Integer.parseInt(tfPrice.getText()),Integer.parseInt(tfqty.getText()));
            OrderGUI f = new OrderGUI();
            f.show();
            this.dispose();
        }else if(e.getSource()==btBasket){
            try {
                basketPd();
                JOptionPane.showMessageDialog(this, "해당 상품이 장바구니에 담겼습니다.");
                int type=JOptionPane.showConfirmDialog(this, "장바구니로 이동하시겠습니까?","확인 여부",JOptionPane.YES_NO_OPTION);
                if(type==JOptionPane.YES_OPTION){
                    BasketGUI f =new BasketGUI();
                    f.show();
                    this.dispose();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
        }
    }

    private void showPd() throws SQLException {
        MarketService ms=new MarketService();
        
        ViewDTO dto=marketDao.selectByPdNo(ms.getPdno());
        
        tfpdName.setText(dto.getPdName());
        tfPrice.setText(dto.getPrice()+"");
//        lbImg=new 
        tfFSize.setText(dto.getFsize());
        tfEatage.setText(dto.getEatage());
        tfPredisease.setText(dto.getPredisease());
        tfKcal.setText(dto.getKcal()+"");
        tfGrade.setText(dto.getGrade()+"");
    }

    private void showPdReview() throws SQLException {
        ReviewsDAO reviewsDao=new ReviewsDAO();
        
        List<ViewDTO> list=reviewsDao.selectPdReview();
        
        String[] colNames={"닉네임","리뷰","평점","등록일"};
        String[][] data = new String[list.size()][colNames.length];
        for(int i=0;i<list.size();i++){
            ViewDTO dto=list.get(i);
            
            data[i][0]=dto.getNickName();
            data[i][1]=dto.getReviewbody();
            data[i][2]=dto.getGrade()+"";
            data[i][3]=dto.getRegdate()+"";
        }
        model.setDataVector(data, colNames);
        tbReviews.setModel(model);
    }

    private void basketPd() throws SQLException {
        int pdno=MarketService.getPdno();
        String qty=tfqty.getText();
        String price=tfPrice.getText();
        int personno = PersonService.getPersonno();
        MarketService.setPrice(Integer.parseInt(price));
        MarketService.setQty(Integer.parseInt(price));
        
        if(qty==null || qty.isEmpty()){
            JOptionPane.showMessageDialog(this, "수량을 입력해주세요");
        }
        
        BasketDTO dto = new BasketDTO(Integer.parseInt(qty), pdno, personno);
      
        BasketDAO basketDao=new BasketDAO();
        basketDao.insertBasketPd(dto);
    }
    
}
