/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.semi.view;

import com.semi.orderdetails.model.OrderdetailsDAO;
import com.semi.person.model.PersonService;
import com.semi.reviews.model.ReviewsDTO;
import com.semi.view.model.ViewDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pjm02
 */
public class OrderDetailsGUI extends javax.swing.JFrame implements ActionListener{
    private DefaultTableModel model=new DefaultTableModel();
    private int pdno;
    /**
     * Creates new form OrderDetailsGUI
     */
    public OrderDetailsGUI() {
        initComponents();
        
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        plReview = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taBody = new javax.swing.JTextArea();
        btRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfProduct = new javax.swing.JTextField();
        tfGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btMain = new javax.swing.JButton();
        btMydata = new javax.swing.JButton();
        btMarket = new javax.swing.JButton();
        btBoard = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("주문내역");

        tbOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbOrders);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("주문 내역");

        taBody.setColumns(20);
        taBody.setRows(5);
        jScrollPane3.setViewportView(taBody);

        btRegister.setText("등록");

        jLabel3.setText("주문한 상품 :");

        jLabel4.setText("평 점 (0~5) :");

        javax.swing.GroupLayout plReviewLayout = new javax.swing.GroupLayout(plReview);
        plReview.setLayout(plReviewLayout);
        plReviewLayout.setHorizontalGroup(
            plReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plReviewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btRegister))
                    .addGroup(plReviewLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        plReviewLayout.setVerticalGroup(
            plReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plReviewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(plReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRegister))
        );

        btMain.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btMain.setText("홈");

        btMydata.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btMydata.setText("내 정보");

        btMarket.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btMarket.setText("마켓");

        btBoard.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btBoard.setText("게시판");

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel5.setText("리뷰 쓰기");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btMain, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMydata, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMydata, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBoard;
    private javax.swing.JButton btMain;
    private javax.swing.JButton btMarket;
    private javax.swing.JButton btMydata;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel plReview;
    private javax.swing.JTextArea taBody;
    private javax.swing.JTable tbOrders;
    private javax.swing.JTextField tfGrade;
    private javax.swing.JTextField tfProduct;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        try {
            showOrders();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addEvent() {
        tbOrders.addMouseListener(new EventHandler());
        btRegister.addActionListener(this);
        btBoard.addActionListener(this);
        btMain.addActionListener(this);
        btMarket.addActionListener(this);
        btMydata.addActionListener(this);
    }

    private void reviewRegister() throws SQLException {
        String sgrade=tfGrade.getText();
        String body=taBody.getText();
        int personno=PersonService.getPersonno();
        if(body==null || body.isEmpty() || body.length()<5){
            JOptionPane.showMessageDialog(this, "리뷰 내용을 5글자 이상 입력해주세요.");
            return;
        }
        int grade=Integer.parseInt(sgrade);
        if(!(grade>=0 && grade<=5)){
            JOptionPane.showMessageDialog(this, "평점을 0~5점 사이로 입력해주세요.");
            return;
        }
        
        ReviewsDTO dto=new ReviewsDTO(body, grade, pdno, personno);
        OrderdetailsDAO odDao=new OrderdetailsDAO();
        
        int cnt=odDao.insertReview(dto);
        
        if(cnt>0){
            JOptionPane.showMessageDialog(this, "리뷰가 등록되었습니다.");
        }else {
            JOptionPane.showMessageDialog(this, "리뷰 등록이 실패하였습니다");
        }
        
    }
    
    class EventHandler extends MouseAdapter{

        @Override
        public void mousePressed(MouseEvent e) {
            if(e.getSource()==tbOrders){
                int row=tbOrders.getSelectedRow();
                Object obj=tbOrders.getValueAt(row, 2);
                String pdname=(String)obj;
                tfProduct.setText(pdname);
                
                Object objPdno=tbOrders.getValueAt(row, 1);
                String pdnumber=(String)objPdno;
                pdno=Integer.parseInt(pdnumber);
            }
        }
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btBoard){
            BoarderGUI f=new BoarderGUI();
            f.show();
            this.dispose();
        }else if(e.getSource()==btMarket){
            MarketMainGUI f=new MarketMainGUI();
            f.show();
            this.dispose();
        }else if(e.getSource()==btMydata){
            MemberInfo f =new MemberInfo();
            f.show();
            this.dispose();
        }else if(e.getSource()==btMain){
            this.dispose();
        }else if(e.getSource()==btRegister){
            try {
                reviewRegister();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void showOrders() throws SQLException {
        
        OrderdetailsDAO orderDetailsDao= new OrderdetailsDAO();
        List<ViewDTO> list = orderDetailsDao.selectOD();
        
        String[] colNames={"주문 번호","상품번호","상품명","수량","카테고리","주문날짜"};
        String[][] data=new String[list.size()][colNames.length];
        for(int i =0;i<list.size();i++){
            ViewDTO dto=list.get(i);
            
            data[i][0]=dto.getOrderno()+"";
            data[i][1]=dto.getPdno()+"";
            data[i][2]=dto.getPdName();
            data[i][3]=dto.getOrderdtqty()+"";
            data[i][4]=dto.getPdcategory();
            data[i][5]=dto.getRegdate()+"";
        }
        model.setDataVector(data, colNames);
        tbOrders.setModel(model);
                
    }
}
