/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.semi.view;

import com.semi.pay.model.PayDAO;
import com.semi.pay.model.PayDTO;
import com.semi.person.model.PersonService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author pjm02
 */
public class Pay extends javax.swing.JFrame implements ActionListener{
    private JPasswordField pwdField = new JPasswordField();
    private OrderGUI orderGui;
    private MemberInfo memberInfo;
    /**
     * Creates new form Card
     */
    public Pay() {
        initComponents();
        
        init();
        addEvent();
    }
    
    public Pay(OrderGUI orderGui) {
        this();
        this.orderGui=orderGui;
    }
    
    public Pay(MemberInfo memberInfo) {
        this();
        this.memberInfo=memberInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfCard1 = new javax.swing.JTextField();
        tfCard2 = new javax.swing.JTextField();
        tfCard3 = new javax.swing.JPasswordField();
        tfCard4 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        tfExpiration = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCvc = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        tfCardPwd = new javax.swing.JPasswordField();
        btCardRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfCardCom = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("카드 등록");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel2.setText("카드 정보를 입력해주세요");

        jLabel1.setText("카드 번호");

        jLabel3.setText("유효 기간");

        jLabel4.setText("(MMYY)");

        jLabel5.setText("cvc");

        jLabel6.setText("카드 비밀번호 4자리");

        btCardRegister.setText("등록");

        jLabel7.setText("-");

        jLabel8.setText("-");

        jLabel9.setText("-");

        jLabel10.setText("카드회사");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCardRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCardPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(tfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCvc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(tfCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tfCard4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfCardCom))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCard1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(tfCard2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(tfCard3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(tfCard4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(tfCardPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(tfCardCom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btCardRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCardRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfCard1;
    private javax.swing.JTextField tfCard2;
    private javax.swing.JPasswordField tfCard3;
    private javax.swing.JPasswordField tfCard4;
    private javax.swing.JTextField tfCardCom;
    private javax.swing.JPasswordField tfCardPwd;
    private javax.swing.JPasswordField tfCvc;
    private javax.swing.JPasswordField tfExpiration;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    private void addEvent() {
        btCardRegister.addActionListener(this);
        tfCard1.addKeyListener(new EventHandler());
        tfCard2.addKeyListener(new EventHandler());
        tfCard3.addKeyListener(new EventHandler());
        tfCard4.addKeyListener(new EventHandler());
        tfExpiration.addKeyListener(new EventHandler());
        tfCvc.addKeyListener(new EventHandler());
        tfCardPwd.addKeyListener(new EventHandler());
        tfCardCom.addActionListener(this);
    }
    
    private boolean isNum(String str) {
        boolean bool=false;
        for(int i=0;i<str.length();i++){
            char ch=str.charAt(i);
            if(!(ch>='0' && ch<='9')){
                bool=false;
                return bool;
            }else{
                bool=true;
            }
        }
        return bool;
    }
    
    class EventHandler extends KeyAdapter{

        @Override
        public void keyReleased(KeyEvent e) {
            if(tfCard1.getText().length()==4){
                tfCard2.requestFocus();
            }
            if(tfCard2.getText().length()==4){
                tfCard3.requestFocus();
            }
            if(tfCard3.getText().length()==4){
                tfCard4.requestFocus();
            }
            if(tfCard4.getText().length()==4){
                tfExpiration.requestFocus();
            }
            if(tfExpiration.getText().length()==4){
                tfCvc.requestFocus();
            }
            if(tfCvc.getText().length()==3){
                tfCardPwd.requestFocus();
            }
            if(tfCardPwd.getText().length()==4){
                tfCardCom.requestFocus();
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==tfCardCom || e.getSource()==btCardRegister){
            try {
                cardRegister();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void cardRegister() throws SQLException {
        String cardNo=tfCard1.getText()+"-"+tfCard2.getText()+"-"+tfCard3.getText()+"-"+tfCard4.getText();
        String expiration = tfExpiration.getText();
        String cvc=tfCvc.getText();
        String pwd=tfCardPwd.getText();
        String com=tfCardCom.getText();
        
        if(cardNo.length()<19){
            JOptionPane.showMessageDialog(this, "카드번호를 입력해주세요");
            return;
        }else if(cardNo.length()>19){
            JOptionPane.showMessageDialog(this, "카드번호를 잘못 입력했습니다.");
            return;
        }
        
        if(expiration==null || expiration.isEmpty() || expiration.length()!=4){
            JOptionPane.showMessageDialog(this, "유효 기간 4자리를 입력해주세요");
            return;
        }
        
        if(cvc==null || cvc.isEmpty() || cvc.length()!=3){
            JOptionPane.showMessageDialog(this, "cvc 3자리를 입력해주세요");
            return;
        }
        String card1=tfCard1.getText();
        String card2=tfCard2.getText();
        String card3=tfCard3.getText();
        String card4=tfCard4.getText();
        
        boolean bool1=isNum(cvc);
        boolean bool2=isNum(card1);
        boolean bool3=isNum(card2);
        boolean bool4=isNum(card3);
        boolean bool5=isNum(card4);
        boolean bool6=isNum(expiration);
        boolean bool7=isNum(pwd);
        
        
        if(bool1==false || bool2==false || bool3==false || bool4==false || bool5==false || bool6==false || bool7==false){
            JOptionPane.showMessageDialog(this,"숫자를 입력해주세요");
            if(bool1==false){
                tfCvc.requestFocus();
            }else if(bool2==false){
                tfCard1.requestFocus();
            }else if(bool3==false){
                tfCard2.requestFocus();
            }else if(bool4==false){
                tfCard3.requestFocus();
            }else if(bool5==false){
                tfCard4.requestFocus();
            }else if(bool6==false){
                tfExpiration.requestFocus();
            }else if(bool7==false){
                tfCardPwd.requestFocus();
            }
            
            return;
        }
        pwdField = new JPasswordField();
        int option = JOptionPane.showConfirmDialog(this, pwdField, "카드 결제 비밀번호 6자리 등록 ", JOptionPane.OK_OPTION);
        String payPwd="";
        if (option == JOptionPane.OK_OPTION) {
            payPwd = pwdField.getText();
        }else {
            return;
        }
        
        if(payPwd==null || payPwd.isEmpty() || payPwd.length()!=6){
            JOptionPane.showMessageDialog(this, "카드 결제 비밀번호가 6자리가 아닙니다.");
            return;
        }
        boolean bool8=isNum(payPwd);
        if(bool8==false){
            JOptionPane.showMessageDialog(this,"카드 결제 비밀번호가 숫자가 아닙니다.");
            return;
        }
        
        if(tfCard1.getText().length()!=4){
            tfCard1.requestFocus();
        }else if(tfCard2.getText().length()!=4){
            tfCard2.requestFocus();
        }else if(tfCard3.getText().length()!=4){
            tfCard3.requestFocus();
        }else if(tfCard4.getText().length()!=4){
            tfCard4.requestFocus();
        }
        
        PayDTO dto=new PayDTO();
        dto.setCardno(cardNo);
        dto.setCardcom(com);
        dto.setCvc(cvc);
        dto.setExpiration(expiration);
        dto.setCardpassword(pwd);
        dto.setPersonno(PersonService.getPersonno());
        dto.setPaypassword(payPwd);
        System.out.println("dto="+dto);
        PayDAO payDao=new PayDAO();
        int cnt=payDao.insertCard(dto);
        
        if(cnt>0){
            JOptionPane.showMessageDialog(this, "카드가 등록되었습니다.");
            this.dispose();
            
            if(orderGui!=null){
                orderGui.tfCardCom.setText(tfCardCom.getText());
                orderGui.tfCvc.setText(tfCvc.getText());
                orderGui.tfExpiration.setText(tfExpiration.getText());
                String cardNo2=tfCard1.getText()+"-"+tfCard2.getText()+"-"+tfCard3.getText()+"-"+tfCard4.getText();
                orderGui.tfCardNo.setText(cardNo2);
            }else{
                memberInfo.setPayValue();
            }
        }else{
            JOptionPane.showMessageDialog(this, "카드 등록 실패");
        }
    }
}
